# Generated by Django 5.1.1 on 2024-09-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('bills', 'Bills'), ('housing', 'Housing'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('others', 'Others')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
